### ISSUE TITLE
[help required] please improve create_service example when wsdl doesn't define any service elements.

### ISSUE THREAD

**Issue by andreabisello** [mvantellingen/python-zeep#1104]
using latest version of zeep in python 3.8

this wsdl

https://testwslegalmobile.solutiondocondemand.com/Service.svc?singlewsdl

doesn't have any service element (even if i paste in soapui client)

following this documentation https://docs.python-zeep.org/en/master/client.html#creating-new-serviceproxy-objects i will able to change soap address , but in my case there is any service element so this syntax

```

zeep_client = Client(ENDPOINT)
binding_qname = '{http://tempuri.org/}wslegalmobile'
service = zeep_client.create_service(binding_qname,ENDPOINT)


```

returns :

ValueError: No binding found with the given QName. Available bindings are:

i know: there is no binding, i would like to create one.

any suggestion please?

thanks

**Comment by da1910** [comment]
My understanding is that since the WSDL defines neither a service nor bindings there is no straightforward way to create the services needed. Is the service owner able to provide the bindings for you?

In terms of workarounds: if the API specification does not change often then you could copy the wsdl locally and manually add the service definition. It would be fairly trivial to do this in python, knowing the endpoint address, the other information should be available.

As an example (using one operation from your wsdl), I believe the binding would look like
```
<binding name="IServiceBinding" type="tns:IService">
  <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
  <wsaw:UsingAddressing wsdl:required="true" />
  <operation name="Login">
    <soap:operation soapaction="http://tempuri.org/IService/Login" />
    <input> 
      <soap:body use="literal" />
    </input> 
    <output>
      <soap:body use="literal" />
    </output>
  </operation>
</binding>
```

This should be fairly easy to iterate through the portType specification in the wsdl with some basic lxml, the only elements that would vary are the operation name and the soap action.

Once the bindings are created then you should be able to use the create_service call as you suggested above, and you should be able to get underway.

**Comment by andreabisello** [comment]
@da1910  thanks for your advice. how can i locally load the wsdl definition?

**Comment by da1910** [comment]
When you create the client object you can pass a local path, relative to your current working directory, exactly as you have done with the URL.

**Comment by da1910** [comment]
Did you manage to get this working in the end? If so it's helpful to close the ticket so others know that the issue is resolved

**Comment by andreabisello** [comment]
@da1910  it work,
i locally downloaded the wsdl, i made a manual update (the wsdl will not be updated often)  and i used it.
many thanks
