### ISSUE TITLE
 DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by andreabisello** [mvantellingen/python-zeep#1388]
`Lib\site-packages\zeep\utils.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13`

**Comment by akeeman** [comment]
duplicate of https://github.com/mvantellingen/python-zeep/issues/1352 and fixed in d0d737adbcd68213b940a5cc4f1da6cd43dfca81 (https://github.com/mvantellingen/python-zeep/pull/1364)

**Comment by jbwalker26** [comment]
Please release this change.  We use `zeep` and we do not want to hold up keeping our code in a well-maintained state.

**Comment by ehiggs** [comment]
>  3.13 has been out for a while and this seems to be only required change.

Python 3.13 has no been released yet. The release schedule is [here](https://peps.python.org/pep-0719/)

**Comment by jbwalker26** [comment]
> Python 3.13 has not been released yet.

That might be the case; but it has been in alpha for a year, and it is well recognized that `cgi` is not supported in Python 3.13.  It is ridiculous that the fix is already merged a while ago, but it is yet to be released.

They may have a few months to put it together, granted.  But then again, they only have a few months to put it together.

**Comment by gsauthof** [comment]
FWIW, Fedora Rawhide recently imported Python 3.13 (beta) such that issues can be fixed in time for Fedora 41.

Due to this issue the Fedora zeep package currently fails to build and I have to integrate the linked commit instead of simply bumping the package to a new release.

**Comment by IvanciuVlad** [comment]
Hi, Py 3.13 is due to be released on October 1st. Having an official release would definitely simplify our migration to the new env. Don't want to be pushy, but there already is a fix for the deprecation issue, and we would prefer not having to build our own package.

**Comment by andreabisello** [comment]
guys that's an open source software, we  should really thanks @mvantellingen  for what I have done until now, and we should simply blame who has not passed to Rest api and still using soap. Anyway, @IvanciuVlad  go for  a venv with python 3.12 or try to fix the problem with cgi. here there are alternatives https://peps.python.org/pep-0594/#cgi

**Comment by pulse-mind** [comment]
I was asking the same question "who has not passed to Rest API and still using SOAP" :D until I had no choice to implement a client for a web-services that was using SOAP...
Anyway this is not the problem here. The bug is fixed and merged. There is a need to release it as [akeeman](https://github.com/akeeman) already explained at the beginning : "duplicate of https://github.com/mvantellingen/python-zeep/issues/1352 and fixed in https://github.com/mvantellingen/python-zeep/commit/d0d737adbcd68213b940a5cc4f1da6cd43dfca81 (https://github.com/mvantellingen/python-zeep/pull/1364)"

**Comment by andreabisello** [comment]
https://github.com/mvantellingen/python-zeep/issues/1388#issuecomment-1730161369
