### ISSUE TITLE
Zeep is posting to HTTP, despite an https wsdl location

### ISSUE THREAD

**Issue by graham-m-dunn** [mvantellingen/python-zeep#228]
zeep 0.18.1 via pip install

``` python
client = zeep.Client(wsdl='https://kik.vidyocloud.com/services/v1_1/VidyoPortalUserService?wsdl', transport=transport_with_basic_auth)

>>> result = client.service.createScheduledRoom()
zeep.transports: HTTP Post to http://kik.vidyocloud.com/services/v1_1/VidyoPortalUserService/:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns0="http://portal.vidyo.com/user/v1_1" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:CreateScheduledRoomRequest/>
  </soap-env:Body>
</soap-env:Envelope>

zeep.transports: HTTP Response from http://kik.vidyocloud.com/services/v1_1/VidyoPortalUserService/ (status: 500):
<faultstring>The endpoint reference (EPR) for the Operation not found is /services/v1_1/VidyoPortalUserService/ and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.</faultstring>
```

with suds, I could pass a location= argument in the Client() constructor and it would post to the https endpoint.  Is there something similar in zeep?

**Comment by mvantellingen** [comment]
Yeah, so the issue is that the wsdl is loaded via https but the actually bindings are using http. My idea is to force all bindings on https if the wsdl is retrieved via https. But need to find some time for this.

For now you can register your own binding and use https, see http://docs.python-zeep.org/en/master/in_depth.html#creating-new-service-objects

**Comment by mvantellingen** [comment]
Zeep no always forces the bindings to use https when the wsdl is loaded from https.
