### ISSUE TITLE
Adding to cache breaks in python3

### ISSUE THREAD

**Issue by mcordes** [mvantellingen/python-zeep#48]
~~Howdy. I'm running into an issue with the latest code in SqliteCache.~~

Please ignore, the issue was on my end.

**Comment by mcordes** [comment]
Scratch that. I'm pretty sure the issue is that I'm storing both python2 and python3 data in the same cache. 

Please ignore.

**Comment by mvantellingen** [comment]
Yeah it is actually an issue I've run into myself a couple of times. Need to mark the cache entries with the python and zeep version

**Comment by mcordes** [comment]
That works too. Thanks!

**Comment by nicoe** [comment]
I must say that I don't understand the need to mark cache entries with the python version. IIUC zeep is caching the content of the wsdl thus for me this data is unrelated to a python version.

That being said, I have taken a look and notice that if the database is created from python2 then `unicode` are retrieved afterwards in python2 and `str` in python3.

If the database is created from python3 then `bytes` are retrived by python3 and `buffer` in case of python2.

In both case the `_decode_data()` call will fail. I think that what should be stored should be consistent and thus since it is base64 data I would always use bytes (encoding to `ascii` and wrapping it in a buffer when in python2 should do the trick I think).

What do you think about this?

**Comment by mvantellingen** [comment]
Hi @nicoe, that sounds like the better solution indeed. Do you want to create a PR for this?

**Comment by nicoe** [comment]
* Michael van Tellingen  [2016-06-02 21:01 +0200]: 
>Hi @nicoe, that sounds like the better solution indeed. Do you want to create a PR for this?

Yep, I'll try to work on it this weekend.

**Comment by mvantellingen** [comment]
merged 👍
