### ISSUE TITLE
Problem with ValidationError exception (minOccurs check)

### ISSUE THREAD

**Issue by Neiby** [mvantellingen/python-zeep#500]
This is a question more than a bug report. I have no reason to think there is a bug yet. I'm new to SOAP, so I'm not really sure what I'm running into. I've written a test script using zeep 2.2.0 to initialize and then execute an export request from an IP Control server (IP address management tool). In response to executing the export (`client.service.exportChildBlock()`), I get the following traceback:

  ```
File "/usr/local/lib/python3.6/site-packages/zeep/xsd/elements/any.py", line 164, in validate
    "Expected at least %d items (minOccurs check)" % self.min_occurs)
zeep.exceptions.ValidationError: Expected at least 1 items (minOccurs check)
```

Full traceback: https://gist.github.com/Neiby/42d52b42c9d95e307080254dee55655e

WSDL:  https://gist.github.com/Neiby/3825b8d6db486d6a9063b15b08e5ce93

Here is my simple test script:

```
from creds import user, pw
from zeep import Client
from requests import Session
from requests.auth import HTTPBasicAuth
from zeep import Client
from zeep.transports import Transport


session = Session()
session.auth = HTTPBasicAuth(user, pw)
client = Client('http://ipcontrol.foobar.net/inc-ws/services/Exports?wsdl',
                 transport=Transport(session=session),
                 strict=False)

query_parameters = ('ipaddress=1.2.3.4',
                    'includeFreeBlocks=False')

context = client.service.initExportChildBlock(*query_parameters)
result = client.service.exportChildBlock(context)
```

Since I'm new to both SOAP and zeep, I have no idea where to go from here. The exception clearing is telling me that I have zero somethings when I should have at least one something, but I don't know the details. I really didn't want to create an issue on github, but I couldn't find any other place to ask this question. If there is a better place for questions, please let me know.

Thanks!

**Comment by aficustree** [comment]
wow, a fellow IPControl user dealing with this terrible Axis SOAP API. I'm basically at the exact same spot (FYI, you'll run into an issue with needing to pull out the SessionID from the header and manually add it to the request in exportChildBlock). That said, did you ever figure this out? The issue is with the WSDL not expecting an empty options array. I don't know how to fix it though. I tried to go into the client.wsdl and change the minOccurs but types is an iterator and i figured there had to be a better way than iterating until i found the options type and overriding it.

**Comment by Neiby** [comment]
I fixed it by switching to Python2.7 and using the suds module.  :(  But I
did get it to work. I found an old post on Stack Overflow who had problems,
as well, so I borrowed code from numerous places including a semi-working
PHP script and got something to work. This is an example of doing a simple
container export based on IP address.

https://stackoverflow.com/questions/29433648/soap-suds-ipcontrol-exportdevice/45201107#45201107

I can't remember if I tried this exact script in Python 3.6 yet. That's
what I normally use, but I seem to recall suds had a problem when I tried
it in 3.6. I wish zeep worked so I could stick to 3.6, but I don't know
enough about SOAP or zeep to figure this out on my own.

**Comment by aficustree** [comment]
Cool. I'll keep at it for a bit longer out of sheer stubbornness. I have a C# library for this exact purpose (which also required an absurd amount of troubleshooting but we need to move it to python for various reasons. If I can just figure out how to get deep to allow minOccurs=0 on the WSContext type i think it'll work. If you ever need the C#/.NET 4.5 way to get it working just let me know, i'll send you what i have.

**Comment by Neiby** [comment]
I can spell C# and .NET, but that's about it!  lol   I don't know if my
code will help since this seems to be a zeep-specific issue, but maybe it
might spark an idea. Who knows. If you get it working in zeep, definitely
let me know so I can switch this back to Python 3.6. Good luck!

**Comment by aficustree** [comment]
I seem to have figured it out,

0. call the init
`response=self._client.service.initExportChildBlock("container='SEARCHSTRING' and recursive='container'", False)`
1. pull the SessionID header off the last message received:
`history = zeep.plugins.HistoryPlugin()
header=history.last_received['envelope'].find(".//{http://xml.apache.org/axis/session}sessionID")`
2. since the WSContext object has it as 'nilable' we can sidestep the whole problem by simply skipping the problematic null array
`response.options=xsd.SkipValue`
3. then call like:
`response2=self._client.service.exportChildBlock(response, _soapheaders=[header])`

Still don't know how to edit the WSDL once loaded but this technique side steps the problem

**Comment by Neiby** [comment]
Based on that, I'm trying the following and running into an error:

```
response = client.service.initExportChildBlock(*query_parameters)

history = HistoryPlugin() 
header = history.last_received['envelope'].find(".//{http://xml.apache.org/axis/session}sessionID")
response.options=xsd.SkipValue

result = client.service.exportChildBlock(response, _soapheaders=[header])
```

That results in the following error:

```    header = history.last_received['envelope'].find(".//{http://xml.apache.org/axis/session}sessionID")
  File "/usr/local/lib/python3.6/site-packages/zeep/plugins.py", line 61, in last_received
    last_tx = self._buffer[-1]
IndexError: deque index out of range```

Any thoughts on that? I appreciate the help! I'd love to get this working in Python3.6. Having no experience with SOAP is making it a difficult process.

**Comment by Neiby** [comment]
Scratch that. I had neglected to add `plugins=[history]` in the client.

**Comment by mvantellingen** [comment]
I really need a runnable example script for this, otherwise i cannot help you with the issue :-(
