### ISSUE TITLE
Question: Why Cyrillic symbols converted to html entities?

### ISSUE THREAD

**Issue by marker91** [mvantellingen/python-zeep#505]
Hi, @mvantellingen

I trying pass str in object attribute with cyrillic symbols, but after call create_message() i get html entities instead cyrillic symbols, what am I doing wrong?

**Comment by marker91** [comment]
@mvantellingen 

example:
`client = Client('http://www.webservicex.net/ConvertSpeed.asmx?WSDL')
print(etree.tostring(client.create_message(client.service, "ConvertSpeed", 100, 'тестоваястрока', 'milesPerhour')))`
print:
`<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:ConvertSpeed xmlns:ns0="http://www.webserviceX.NET/"><ns0:speed>100</ns0:speed><ns0:FromUnit>&#1099;&#1074;&#1092;&#1099;&#1074;&#1092;&#1099;&#1074;</ns0:FromUnit><ns0:ToUnit>milesPerhour</ns0:ToUnit></ns0:ConvertSpeed></soap-env:Body></soap-env:Envelope>`

IDE: PyCharm, Project Encoding: <System Default: windows-1251>

**Comment by penguinolog** [comment]
`>>> xml.etree.ElementTree.tostring(msg)`
`b'<ns0:Envelope xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://www.webserviceX.NET/"><ns0:Body><ns1:ConvertSpeed><ns1:speed>100</ns1:speed><ns1:FromUnit>&#1090;&#1077;&#1089;&#1090;&#1086;&#1074;&#1072;&#1103;&#1089;&#1090;&#1088;&#1086;&#1082;&#1072;</ns1:FromUnit><ns1:ToUnit>milesPerhour</ns1:ToUnit></ns1:ConvertSpeed></ns0:Body></ns0:Envelope>'
`
Bytes object is returned. Using direct access, i receive:
`>>> f.text`
`'тестоваястрока'`

Using lxml instead of xml.
`>>> lxml.etree.tostring(msg)`
`b'<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:ConvertSpeed xmlns:ns0="http://www.webserviceX.NET/"><ns0:speed>100</ns0:speed><ns0:FromUnit>&#1090;&#1077;&#1089;&#1090;&#1086;&#1074;&#1072;&#1103;&#1089;&#1090;&#1088;&#1086;&#1082;&#1072;</ns0:FromUnit><ns0:ToUnit>milesPerhour</ns0:ToUnit></ns0:ConvertSpeed></soap-env:Body></soap-env:Envelope>'`

`>>> lxml.etree.tounicode(msg)`
`'<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:ConvertSpeed xmlns:ns0="http://www.webserviceX.NET/"><ns0:speed>100</ns0:speed><ns0:FromUnit>тестоваястрока</ns0:FromUnit><ns0:ToUnit>milesPerhour</ns0:ToUnit></ns0:ConvertSpeed></soap-env:Body></soap-env:Envelope>'`

Resume: Not a bug.

**Comment by marker91** [comment]
@penguinolog  Thx, Alexey =)
