### ISSUE TITLE
cannot install zeep[xmlsec]

### ISSUE THREAD

**Issue by lopow** [mvantellingen/python-zeep#611]
I run to this problem,  when I want to install: pip install zeep[xmlsec]

    fatal error C1047: The object or library file 'build\extra\iconv-1.14.win64\lib\iconv_a.lib' was created with an older compiler than other objects; rebuild old objects and libraries
    LINK : fatal error LNK1257: code generation failed
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\link.exe' failed with exit status 1257

**Comment by vladimir-chernenko** [comment]
Hi, @lopow your error is not connected  with zeep, but with Visual Studio itself. 
Please read [this stack-overflow question](https://stackoverflow.com/questions/837073/error-c1047-object-file-created-with-an-older-compiler-than-other-objects)

You need to reinstall Visual studio because of libs inconsistency

**Comment by lopow** [comment]
Super, thats works.
